version: '3'
services:
  db:
    image: postgres:10
    environment:
      - "POSTGRES_DB"
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "PGDATA=/var/lib/postgresql/data"
    volumes:
      - ./mnt/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # To build with gunicorn, use the following dockerfile.
      #dockerfile: Dockerfile.gunicorn
    command: "python manage.py runserver 0.0.0.0:$APP_PORT"
    # To serve with gunicorn, use the following command.
    #command: "/usr/local/bin/gunicorn -c gunicorn.conf.py sunrise.wsgi:application -b 0.0.0.0:$APP_PORT"
    environment:
      - "DB_HOST"
      - "DB_NAME"
      - "DB_USER"
      - "DB_PASSWORD"
      - "DB_PORT"
      - "APP_DEBUG"
      - "ALLOWED_HOSTS"
      - "APP_SECRET_KEY"
      - "APP_PORT"
      - "MAP_CENTER"
      - "MAP_COLOR"
    volumes:
      - .:/sunrise
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
